name: Actions Workflow

on:
  #   schedule:
  # - cron: "0/5 * * * *"
  # - cron: "0/6 * * * *"
  # push:
  repository_dispatch:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        shell: bash
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        shell: bash
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/javascript-action@v1
        with:
          who-to-greet: Eshun
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
