name: Actions Workflow

on:
  push: # works for pull requests also
    branches:
      - master
      - "feature/*" # maches all branches with the start name to be features but does not match feature/feat/featA
      - "feature/**" # this will accomodate the match feature/feat/featA
      - "!feature/featC" # ignoring the branch if pushed
    tags:
      - v1.* #running on all tags for v1 ++
    paths:
      - "**.js" # allowed to run workflow only if we change/push the javascript files
  #   schedule:
  # - cron: "0/5 * * * *"
  # - cron: "0/6 * * * *"
  # push:
  # repository_dispatch:
  #   types: [build]
  # pull_request:
  #   types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        shell: bash
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        shell: bash
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/javascript-action@v1
        with:
          who-to-greet: Eshun
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
