name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: windows
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiple scripts
        run: |
          node -v
          npm -v
